// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import slack "github.com/nlopes/slack"

// ConversationMemberFinder is an autogenerated mock type for the ConversationMemberFinder type
type ConversationMemberFinder struct {
	mock.Mock
}

// GetUsersInConversation provides a mock function with given fields: params
func (_m *ConversationMemberFinder) GetUsersInConversation(params *slack.GetUsersInConversationParameters) ([]string, string, error) {
	ret := _m.Called(params)

	var r0 []string
	if rf, ok := ret.Get(0).(func(*slack.GetUsersInConversationParameters) []string); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(*slack.GetUsersInConversationParameters) string); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*slack.GetUsersInConversationParameters) error); ok {
		r2 = rf(params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
