name: Deploy on new Tag

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Install landler
        run: GOBIN=${GITHUB_WORKSPACE}/bin/ go install github.com/alexandre-normand/landler

      - name: Prepare dependencies for gcloud deploy
        run: cd ${GITHUB_WORKSPACE}/cloudfunctions && go mod init github.com/${GITHUB_REPOSITORY}/cloudfunctions && go mod edit -replace github.com/alexandre-normand/rogerchallenger=../ && go build . && go mod vendor

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'          
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - run: cd $GITHUB_WORKSPACE/cloudfunctions && ${GITHUB_WORKSPACE}/bin/landler | xargs -I % gcloud functions deploy % --runtime go111 --trigger-http --allow-unauthenticated
