name: Deploy on new Tag

on:
  push:
    tags: ['*']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:        
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          ref: $GITHUB_REF

      - name: Install landler
        run: go install github.com/alexandre-normand/landler

      - name: Prepare dependencies for gcloud deploy
        run: cd $GITHUB_WORKSPACE/cloudfunctions && \
             go mod init github.com/$GITHUB_REPOSITORY/cloudfunctions && \
             go build . && \
             go mod vendor

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'          
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - run: cd $GITHUB_WORKSPACE/cloudfunctions && landler | xargs -I % gcloud functions deploy % --runtime go111 --trigger-http --allow-unauthenticated
