name: Deploy

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          ref: $GITHUB_REF

      - name: Install landler
        run: go install github.com/alexandre-normand/landler

      - name: Prepare dependencies for gcloud deploy
        run: cd $GITHUB_WORKSPACE/cloudfunctions && \
             go mod init github.com/$GITHUB_REPOSITORY/cloudfunctions && \
             go build . && \
             go mod vendor

      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: rogerchallenger
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: cd $GITHUB_WORKSPACE/cloudfunctions && landler | xargs -I % gcloud functions deploy % --runtime go111 --trigger-http --allow-unauthenticated
